# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AutoSpectral
                                 A QGIS plugin
 ---
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-13
        copyright            : (C) 2025 by JokAlex
        email                : ---
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "JokAlex"
__date__ = "2025-12-09"
__copyright__ = "(C) 2025 by JokAlex"


import qgis.gui


# noinspection PyPep8Naming
def classFactory(iface: qgis.gui.QgisInterface):  # pylint: disable=invalid-name
    """Loads ThresholdPlugin class from file threshold_plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgisInterface
    """
    from .threshold_plugin import ThresholdPlugin

    return ThresholdPlugin()
