# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AutoSpectral
                                 A QGIS plugin
 ---
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-13
        copyright            : (C) 2025 by JokAlex
        email                : ---
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "JokAlex"
__date__ = "2025-10-13"
__copyright__ = "(C) 2025 by JokAlex"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import qgis.core, qgis.processing


class ThresholdAlgorithm(qgis.core.QgsProcessingAlgorithm):
    SOURCE_RASTER = "SOURCE_RASTER"
    SOURCE_BAND = "SOURCE_BAND"
    THRESHOLD = "THRESHOLD"
    OUTPUT = "OUTPUT"

    def initAlgorithm(self, configuration=None):
        """
        Initializes the threshold algorithm, creating parameters.
        """
        self.addParameter(
            qgis.core.QgsProcessingParameterRasterLayer(
                self.SOURCE_RASTER, "Source raster"
            )
        )

        self.addParameter(
            qgis.core.QgsProcessingParameterBand(
                self.SOURCE_BAND, "Source band", 1, self.SOURCE_RASTER
            )
        )

        self.addParameter(
            qgis.core.QgsProcessingParameterNumber(
                self.THRESHOLD,
                "Threshold",
                qgis.core.QgsProcessingParameterNumber.Double,
            )
        )

        self.addParameter(
            qgis.core.QgsProcessingParameterRasterDestination(
                self.OUTPUT, "Binary mask layer"
            )
        )

    def processAlgorithm(
        self,
        parameters: dict[str, str],
        context: qgis.core.QgsProcessingContext,
        feedback: qgis.core.QgsProcessingFeedback,
    ) -> dict[str, str]:
        """
        Runs the threshold algorithm.
        """
        source_layer = self.parameterAsRasterLayer(
            parameters, self.SOURCE_RASTER, context
        )

        source_band = self.parameterAsInt(parameters, self.SOURCE_BAND, context)

        threshold = self.parameterAsDouble(parameters, self.THRESHOLD, context)

        output_path = self.parameterAsOutputLayer(
            parameters, self.OUTPUT, context
        )

        source_band_str = f'"{source_layer.name()}@{source_band}"'
        formula = f"{source_band_str} > {threshold}"

        raster_calc_output = qgis.processing.run(
            "qgis:rastercalculator",
            {
                "LAYERS": [source_layer],
                "EXPRESSION": formula,
                "OUTPUT": output_path,
            },
            feedback=feedback,
            context=context,
            is_child_algorithm=True,
        )

        return {self.OUTPUT: raster_calc_output["OUTPUT"]}

    def name(self) -> str:
        return "threshold"

    def displayName(self) -> str:
        return "Threshold"

    def createInstance(self):
        return ThresholdAlgorithm()
